# Generated by Django 3.1.5 on 2021-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210201_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(default='default_picture.jpeg', max_length='128', upload_to='teachers/'),
        ),
    ]
