# Generated by Django 3.1.5 on 2021-02-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210202_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(default='default_picture.jpeg', upload_to='teachers/'),
        ),
    ]
