# Generated by Django 3.1.5 on 2021-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210202_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.FileField(default='default_picture.jpeg', upload_to='teachers/'),
        ),
    ]
